export type NIMModel = {
  name: string;
  displayName: string;
  namespace: string;
  tags: string[];
  latestTag: string;
  euRestricted: boolean;
};

/**
 * Static model data from the pre-shipped nim-models-data ConfigMap.
 * In production, the Dashboard reads this from a real ConfigMap in the main namespace.
 * Tags are limited to the 5 most recent for display purposes.
 */
export const NIM_MODELS: NIMModel[] = [
  {
    name: "llama-3.1-70b-instruct-pb24h2",
    displayName: "Llama-3.1-70b-instruct PB October 2024 (PB 24h2)",
    namespace: "nim/meta",
    tags: ["1.3.8", "1.3.7", "1.3.6", "1.3.5", "1.3.4"],
    latestTag: "1.3.8",
    euRestricted: false,
  },
  {
    name: "bge-large-zh-v1-5",
    displayName: "bge-large-zh-v1-5",
    namespace: "nim/baai",
    tags: ["1.5", "latest", "1.5.0"],
    latestTag: "1.5.0",
    euRestricted: false,
  },
  {
    name: "llama-3.1-8b-instruct",
    displayName: "Llama-3.1-8B-Instruct",
    namespace: "nim/meta",
    tags: ["1.15.5", "1.15.4", "1.15", "1.13.1", "1.13"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "llama-3.1-swallow-70b-instruct-v0.1",
    displayName: "Llama-3.1-Swallow-70B-Instruct-v0.1",
    namespace: "nim/tokyotech-llm",
    tags: ["1.3.2", "1", "1.3", "latest"],
    latestTag: "1.3.2",
    euRestricted: false,
  },
  {
    name: "deepseek-r1-distill-qwen-14b",
    displayName: "Deepseek-R1-Distill-Qwen-14B",
    namespace: "nim/deepseek-ai",
    tags: ["1.1.0", "1.1", "latest", "1", "1.0"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "flux.1-dev",
    displayName: "flux.1-dev",
    namespace: "nim/black-forest-labs",
    tags: ["1.2", "1.2.0", "1.1.0", "1.1", "1.0.1"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "llama-3.3-nemotron-super-49b-healthcare-text2sql-v1.0",
    displayName: "llama-3.3-nemotron-super-49b-healthcare-text2sql-v1.0",
    namespace: "nim/nvidia",
    tags: ["1.15", "1", "1.15.1", "latest"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "qwen3-32b-dgx-spark",
    displayName: "Qwen3-32B\u00a0NIM for DGX Spark",
    namespace: "nim/qwen",
    tags: ["1.1.0-variant", "1.1", "1.1.0", "1.0", "1.0.0"],
    latestTag: "1.1.0-variant",
    euRestricted: false,
  },
  {
    name: "llm-nim",
    displayName: "Multi-LLM NIM",
    namespace: "nim/nvidia",
    tags: ["1.15.5", "1.15.4", "1.15.3", "1.15.2", "1.15.1"],
    latestTag: "1.15",
    euRestricted: false,
  },
  {
    name: "phi-3-mini-4k-instruct",
    displayName: "Phi-3-Mini-4K-Instruct",
    namespace: "nim/microsoft",
    tags: ["1.2.3", "latest", "1.2", "1"],
    latestTag: "1.2.3",
    euRestricted: false,
  },
  {
    name: "llama-3.3-nemotron-super-49b-v1.5",
    displayName: "Llama-3.3-nemotron-super-49b-v1.5",
    namespace: "nim/nvidia",
    tags: ["1.15.5", "1.15.4", "1.15", "1.14", "1.14.0"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "evo2-40b",
    displayName: "Evo 2 40B",
    namespace: "nim/arc",
    tags: ["2.1", "2.1.0", "2", "2.0", "2.0.0"],
    latestTag: "2",
    euRestricted: false,
  },
  {
    name: "maxine-bnr",
    displayName: "Background Noise Removal (BNR) NIM",
    namespace: "nim/nvidia",
    tags: ["1.0.0", "1", "1.0", "latest"],
    latestTag: "1.0.0",
    euRestricted: false,
  },
  {
    name: "deepseek-r1-distill-llama-8b",
    displayName: "Deepseek-R1-Distill-Llama-8B",
    namespace: "nim/deepseek-ai",
    tags: ["1.8.0-RTX", "1.5.2", "1", "latest", "1.5"],
    latestTag: "1.8.0-RTX",
    euRestricted: false,
  },
  {
    name: "greenmind-medium-14b-r1",
    displayName: "GreenMind-Medium-14B-R1",
    namespace: "nim/greennode",
    tags: ["1.10.1", "1", "1.10", "latest"],
    latestTag: "1.10.1",
    euRestricted: false,
  },
  {
    name: "parakeet-1-1b-rnnt-multilingual",
    displayName: "Parakeet 1.1b RNNT Multilingual Speech to Text",
    namespace: "nim/nvidia",
    tags: ["1.4", "1.4.0", "1.3.0", "1.3", "1.2"],
    latestTag: "1.4.0",
    euRestricted: false,
  },
  {
    name: "audio2face-3d",
    displayName: "Audio2Face-3D",
    namespace: "nim/nvidia",
    tags: ["1.3.16", "1.3.15", "1.3", "1.2.0", "1.2"],
    latestTag: "1.3.16",
    euRestricted: false,
  },
  {
    name: "sarvam-m",
    displayName: "Sarvam-m",
    namespace: "nim/sarvamai",
    tags: ["1.8", "1", "1.8.5", "latest"],
    latestTag: "1.8",
    euRestricted: false,
  },
  {
    name: "nemotron-nano-12b-v2-vl",
    displayName: "NVIDIA-Nemotron-Nano-12B-v2-VL",
    namespace: "nim/nvidia",
    tags: ["1.6.0", "1.6", "1", "latest", "1.5.0"],
    latestTag: "1.6.0",
    euRestricted: false,
  },
  {
    name: "gemma-2-2b-instruct",
    displayName: "Gemma-2-2B-IT",
    namespace: "nim/google",
    tags: ["1", "1.4.0", "1.4", "latest"],
    latestTag: "1.4.0",
    euRestricted: false,
  },
  {
    name: "nvidia-nemotron-nano-9b-v2-dgx-spark",
    displayName: "NVIDIA-Nemotron-Nano-9B-v2-DGX-Spark",
    namespace: "nim/nvidia",
    tags: ["1.0.0-variant", "1.0", "latest", "1"],
    latestTag: "1.0.0-variant",
    euRestricted: false,
  },
  {
    name: "parakeet-ctc-0.6b-vi",
    displayName: "Parakeet CTC 0.6B Vietnames English ASR",
    namespace: "nim/nvidia",
    tags: ["1.1.0", "1.1", "latest", "1.0.0", "1.0"],
    latestTag: "1.1.0",
    euRestricted: false,
  },
  {
    name: "nemoguard-jailbreak-detect",
    displayName: "NemoGuard JailbreakDetect",
    namespace: "nim/nvidia",
    tags: ["1.10.1", "1.10", "latest", "1", "1.0.0"],
    latestTag: "1.10.1",
    euRestricted: false,
  },
  {
    name: "bge-m3",
    displayName: "bge-m3",
    namespace: "nim/baai",
    tags: ["1.5", "latest", "1.5.0"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "cosmos-reason2-2b",
    displayName: "Cosmos Reason-2-2B",
    namespace: "nim/nvidia",
    tags: ["1.6.0", "1.6", "1", "latest"],
    latestTag: "1.6.0",
    euRestricted: false,
  },
  {
    name: "llama-3.1-8b-instruct-pb24h2",
    displayName: "Llama-3.1-8b-instruct PB October 2024 (PB 24h2)",
    namespace: "nim/meta",
    tags: ["1.3.8", "1.3.7", "1.3.6", "1.3.5", "1.3.4"],
    latestTag: "1.3.8",
    euRestricted: false,
  },
  {
    name: "llama-3.1-70b-instruct-pb25h2",
    displayName: "Llama-3.1-70B-Instruct (PB 25h2)",
    namespace: "nim/meta",
    tags: ["1.14.0-pb5.3-stig-fips-x86-64", "1.14.0-pb5.3", "1.14.0-pb5.2", "1.14.0-pb5.1", "1.14.0-pb5.1-stig-fips-x86-64"],
    latestTag: "1.14.0-pb5.3-stig-fips-x86-64",
    euRestricted: false,
  },
  {
    name: "llama3-70b-instruct",
    displayName: "Meta/Llama3-70b-instruct",
    namespace: "nim/meta",
    tags: ["1.0.3", "1.0", "1", "1.0.1", "latest"],
    latestTag: "1.0.3",
    euRestricted: false,
  },
  {
    name: "qwen-2.5-7b-instruct",
    displayName: "Qwen-2.5-7B-Instruct",
    namespace: "nim/qwen",
    tags: ["latest", "1", "1.0", "1.0.0"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "mixtral-8x22b-instruct-v01",
    displayName: "Mixtral-8x22B-Instruct-v0.1",
    namespace: "nim/mistralai",
    tags: ["1.2.2", "1", "1.2", "latest", "1.0.0"],
    latestTag: "1.2.2",
    euRestricted: false,
  },
  {
    name: "nemotron-4-340b-instruct",
    displayName: "nemotron-4-340b-instruct",
    namespace: "nim/nvidia",
    tags: ["latest", "1.1.2", "1.1", "1"],
    latestTag: "1.1.2",
    euRestricted: false,
  },
  {
    name: "nv-embedqa-mistral-7b-v2",
    displayName: "NVIDIA Retrieval QA Mistral 7B Embedding v2",
    namespace: "nim/nvidia",
    tags: ["1.0.1", "1.0.0"],
    latestTag: "1.0.1",
    euRestricted: false,
  },
  {
    name: "llama-3.3-nemotron-super-49b-v1",
    displayName: "Llama-3.3-Nemotron-Super-49B-v1",
    namespace: "nim/nvidia",
    tags: ["1.10.1", "1.10", "1.8.6", "1.8.5", "1.8.4"],
    latestTag: "1.10.1",
    euRestricted: false,
  },
  {
    name: "parakeet-ctc-0.6b-zh-cn",
    displayName: "Parakeet CTC 0.6B Mandarin English ASR",
    namespace: "nim/nvidia",
    tags: ["1.1.0", "1.1", "1.0.0", "1", "1.0"],
    latestTag: "1.1.0",
    euRestricted: false,
  },
  {
    name: "teuken-7b-instruct-commercial-v0.4",
    displayName: "Teuken-7B-instruct-commercial-v0.4",
    namespace: "nim/opengpt-x",
    tags: ["latest", "1.10.1", "1", "1.10"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "nemoretriever-page-elements-v2",
    displayName: "NeMo Retriever Page Elements v2",
    namespace: "nim/nvidia",
    tags: ["1.6", "1.6.0", "1.5.0", "1.5", "1.4.0"],
    latestTag: "1.6",
    euRestricted: false,
  },
  {
    name: "parakeet-ctc-0.6b-zh-tw",
    displayName: "Parakeet CTC 0.6B Taiwanese Mandarin-English ASR",
    namespace: "nim/nvidia",
    tags: ["1.1.0", "1.1", "1.0.0", "1.0", "1"],
    latestTag: "1.1.0",
    euRestricted: false,
  },
  {
    name: "riva_translate_4b_instruct",
    displayName: "Riva_Translate_4B_Instruct_8K",
    namespace: "nim/nvidia",
    tags: ["1.8.5", "1.8", "latest", "1"],
    latestTag: "1.8.5",
    euRestricted: false,
  },
  {
    name: "cosmos-reason1-7b",
    displayName: "Cosmos Reason-1-7B",
    namespace: "nim/nvidia",
    tags: ["1.4.1", "1", "1.4", "latest", "1.4.0"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "llama-3.2-nemoretriever-300m-embed-v1",
    displayName: "NVIDIA Retrieval QA Llama 3.2 300m Embedding v1",
    namespace: "nim/nvidia",
    tags: ["1", "1.9", "1.9.0", "latest"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "alphafold2",
    displayName: "AlphaFold2",
    namespace: "nim/deepmind",
    tags: ["2.1.1", "2.1.0", "2.1", "2.0.0", "2.0"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "megatron-1b-nmt",
    displayName: "NMT Megatron Riva 1b",
    namespace: "nim/nvidia",
    tags: ["1.0", "latest", "1.0.0"],
    latestTag: "1.0.0",
    euRestricted: false,
  },
  {
    name: "bielik-11b-v2.3-instruct",
    displayName: "Bielik-11B-v2.3-Instruct",
    namespace: "nim/speakleash",
    tags: ["1", "1.8.4", "1.8", "latest"],
    latestTag: "1.8",
    euRestricted: false,
  },
  {
    name: "codellama-34b-instruct",
    displayName: "CodeLlama-34B-Instruct",
    namespace: "nim/meta",
    tags: ["latest", "1.2.2", "1", "1.2"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "parakeet-ctc-0.6b-es",
    displayName: "Parakeet CTC 0.6B Spanish English ASR",
    namespace: "nim/nvidia",
    tags: ["1.1.0", "1.1", "latest", "1", "1.0.0"],
    latestTag: "1.1.0",
    euRestricted: false,
  },
  {
    name: "llama3.1-typhoon2-8b-instruct",
    displayName: "Llama3.1-Typhoon2-8B-Instruct",
    namespace: "nim/scb10x",
    tags: ["1.8.5", "1", "1.8", "latest"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "llama-3.1-70b-instruct",
    displayName: "Llama-3.1-70b-instruct",
    namespace: "nim/meta",
    tags: ["1.8.3", "1.15.5", "1.15", "1.15.1", "1.14"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "deepseek-r1-distill-llama-70b",
    displayName: "DeepSeek-R1-Distill-Llama-70B",
    namespace: "nim/deepseek-ai",
    tags: ["1.5", "1", "latest", "1.5.2"],
    latestTag: "1.5.2",
    euRestricted: false,
  },
  {
    name: "nemoretriever-table-structure-v1",
    displayName: "NeMo Retriever Table Structure v1",
    namespace: "nim/nvidia",
    tags: ["1.6", "1.6.0", "1.5.0", "1.5", "1.4"],
    latestTag: "1.6.0",
    euRestricted: false,
  },
  {
    name: "kanana-1.5-8b-instruct-2505",
    displayName: "kanana-1.5-8b-instruct-2505",
    namespace: "nim/kakaocorp",
    tags: ["1", "1.10", "latest", "1.10.1"],
    latestTag: "1.10.1",
    euRestricted: false,
  },
  {
    name: "llama-3.3-nemotron-super-49b-v1.5-pb25h2",
    displayName: "Llama-3.3-nemotron-super-49b-v1.5-PB-25h2",
    namespace: "nim/nvidia",
    tags: ["1.14.0-pb5.3", "1.14.0-pb5.2-stig-fips-x86-64", "1.14.0-pb5.2", "1.14.0-pb5.1-stig-fips-x86-64", "1.14.0-pb5.1"],
    latestTag: "1.14.0-pb5.3",
    euRestricted: false,
  },
  {
    name: "cosmos-embed1",
    displayName: "cosmos-embed1",
    namespace: "nim/nvidia",
    tags: ["1.0.0", "1", "1.0", "latest"],
    latestTag: "1.0.0",
    euRestricted: false,
  },
  {
    name: "deepseek-r1-distill-qwen-32b",
    displayName: "Deepseek-R1-Distill-Qwen-32B",
    namespace: "nim/deepseek-ai",
    tags: ["1.1", "1.1.0", "1.0.0", "latest", "1.0"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "llama-3.2-11b-vision-instruct",
    displayName: "Llama-3.2-11B-Vision-Instruct",
    namespace: "nim/meta",
    tags: ["1.1.1", "1.1.0", "1", "1.1", "latest"],
    latestTag: "1.1.1",
    euRestricted: true,
  },
  {
    name: "codellama-70b-instruct",
    displayName: "CodeLlama-70B-Instruct",
    namespace: "nim/meta",
    tags: ["1.2.2", "1.2", "1", "latest"],
    latestTag: "1.2.2",
    euRestricted: false,
  },
  {
    name: "llama-3.2-3b-instruct",
    displayName: "Llama-3.2-3B-Instruct",
    namespace: "nim/meta",
    tags: ["1.10.1", "1.8.6", "1.8.5", "1.8.4", "1.8.3"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "msa-search",
    displayName: "msa-search",
    namespace: "nim/colabfold",
    tags: ["2.2", "2.2.0", "2.1.0", "2.1", "2.0"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "llama-2-7b-chat",
    displayName: "meta-llama-2-7b-chat",
    namespace: "nim/meta",
    tags: ["1.0.3", "1.0", "1", "latest"],
    latestTag: "1.0.3",
    euRestricted: false,
  },
  {
    name: "llama-2-70b-chat",
    displayName: "meta-llama-2-70b-chat",
    namespace: "nim/meta",
    tags: ["1.0.3", "1.0", "1", "latest"],
    latestTag: "1.0.3",
    euRestricted: false,
  },
  {
    name: "maxine-studio-voice",
    displayName: "Studio Voice",
    namespace: "nim/nvidia",
    tags: ["1.1", "1.1.0", "1.0", "1", "latest"],
    latestTag: "1.1",
    euRestricted: false,
  },
  {
    name: "qwen3.5-397b-a17b",
    displayName: "Qwen3.5-397B-A17B",
    namespace: "nim/qwen",
    tags: ["1.7.0-variant", "latest"],
    latestTag: "1.7.0-variant",
    euRestricted: false,
  },
  {
    name: "whisper-large-v3",
    displayName: "Whisper Large v3 - Speech to Text",
    namespace: "nim/nvidia",
    tags: ["1.4.0", "1.4", "1.3.0", "1.3", "1"],
    latestTag: "1.4.0",
    euRestricted: false,
  },
  {
    name: "arctic-embed-l",
    displayName: "Snowflake Arctic Embed Large Embedding",
    namespace: "nim/snowflake",
    tags: ["1.0.1", "1.0.0"],
    latestTag: "1.0.1",
    euRestricted: false,
  },
  {
    name: "llama-3.1-nemotron-nano-8b-healthcare-text2sql-v1.0",
    displayName: "llama-3.1-nemotron-nano-8b-healthcare-text2sql-v1.0",
    namespace: "nim/nvidia",
    tags: ["1", "latest", "1.15.1", "1.15"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "mistral-large-3-675b-instruct-2512",
    displayName: "mistral-large-3-675b-instruct-2512",
    namespace: "nim/mistralai",
    tags: ["1", "1.6", "latest", "1.6.0"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "openfold3",
    displayName: "OpenFold3",
    namespace: "nim/openfold",
    tags: ["1.3.0", "1.3", "1.2", "1.2.0", "1.1.0"],
    latestTag: "1.3.0",
    euRestricted: false,
  },
  {
    name: "mistral-small-24b-instruct-2501",
    displayName: "mistral-small-24b-instruct-2501",
    namespace: "nim/mistralai",
    tags: ["1.8.4", "1.8", "latest", "1"],
    latestTag: "1.8.4",
    euRestricted: false,
  },
  {
    name: "kimi-k2.5",
    displayName: "kimi-k2.5",
    namespace: "nim/moonshotai",
    tags: ["1.7.0-variant", "latest", "1", "1.7.0", "1.7"],
    latestTag: "1.7.0-variant",
    euRestricted: false,
  },
  {
    name: "mistral-7b-instruct-v0.3",
    displayName: "Mistral-7B-Instruct-v0.3",
    namespace: "nim/mistralai",
    tags: ["1.12.0", "1.12", "1.8", "1.8.4", "1.3.0"],
    latestTag: "1.12.0",
    euRestricted: false,
  },
  {
    name: "riva-translate-1_6b",
    displayName: "Riva Translate 1.6b",
    namespace: "nim/nvidia",
    tags: ["1.5", "1.5.0", "1.0.0", "latest", "1"],
    latestTag: "1.5",
    euRestricted: false,
  },
  {
    name: "llama-2-13b-chat",
    displayName: "meta-llama-2-13b-chat",
    namespace: "nim/meta",
    tags: ["1.0.3", "1", "1.0", "latest"],
    latestTag: "1.0.3",
    euRestricted: false,
  },
  {
    name: "boltz2",
    displayName: "Boltz-2",
    namespace: "nim/mit",
    tags: ["1.5", "1.5.0", "1.4.0", "1.4", "1.3"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "nemoretriever-page-elements-v3",
    displayName: "NeMo Retriever Page Elements v3",
    namespace: "nim/nvidia",
    tags: ["1.7", "1", "latest"],
    latestTag: "1.7",
    euRestricted: false,
  },
  {
    name: "molmim",
    displayName: "MolMIM",
    namespace: "nim/nvidia",
    tags: ["1.0.0"],
    latestTag: "1.0.0",
    euRestricted: false,
  },
  {
    name: "ai-generated-image-detection",
    displayName: "ai-generated-image-detection",
    namespace: "nim/hive",
    tags: ["1", "1.0.0", "latest", "1.0"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "gemma2-9b-cpt-sahabatai-v1-instruct",
    displayName: "Gemma2-9B-CPT-Sahabatai-v1-Instruct",
    namespace: "nim/gotocompany",
    tags: ["1", "latest", "1.8.4", "1.8"],
    latestTag: "1.8.4",
    euRestricted: false,
  },
  {
    name: "llama-3.1-nemoguard-8b-topic-control",
    displayName: "Llama 3.1 NemoGuard 8B Topic Control",
    namespace: "nim/nvidia",
    tags: ["1.10", "1.10.1", "1.0.0", "1.0", "latest"],
    latestTag: "1.10.1",
    euRestricted: false,
  },
  {
    name: "llama-3.2-nv-embedqa-1b-v2-pb25h2",
    displayName: "NVIDIA Retrieval QA Llama 3.2 1B Embedding v2",
    namespace: "nim/nvidia",
    tags: ["1.11.2-stig-fips-x86", "1.11.1-stig-fips-x86", "1.11.0-stig-fips-x86"],
    latestTag: "1.11.2-stig-fips-x86",
    euRestricted: false,
  },
  {
    name: "starcoder2-7b",
    displayName: "Starcoder2-7B",
    namespace: "nim/bigcode",
    tags: ["1.15.5", "1.15.3", "1.15", "1.15.0", "1.14.1"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "llama-3.3-70b-instruct",
    displayName: "Llama-3.3-70b-Instruct",
    namespace: "nim/meta",
    tags: ["1.15.5", "1.15.4", "1.15.1", "1.15", "1.14.0"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "nv-embedqa-e5-v5",
    displayName: "NVIDIA Retrieval QA E5 Embedding v5",
    namespace: "nim/nvidia",
    tags: ["1.10.1", "1.10.0", "1.10", "1.9", "1.9.0"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "llama-3.1-nemotron-70b-instruct",
    displayName: "Llama-3.1-Nemotron-70B-Instruct",
    namespace: "nim/nvidia",
    tags: ["1.2", "1.2.3", "1", "latest"],
    latestTag: "1.2",
    euRestricted: false,
  },
  {
    name: "stockmark-2-100b-instruct",
    displayName: "Stockmark-2-100B-Instruct",
    namespace: "nim/stockmark",
    tags: ["1.12", "1.12.0", "1", "latest"],
    latestTag: "1.12.0",
    euRestricted: false,
  },
  {
    name: "flux.1-kontext-dev",
    displayName: "FLUX.1-Kontext",
    namespace: "nim/black-forest-labs",
    tags: ["1.1.2", "1.1.1", "1.1", "1.1.0", "1"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "llama3-8b-instruct",
    displayName: "Meta/Llama3-8b-instruct",
    namespace: "nim/meta",
    tags: ["1.0.3", "1.0", "1", "latest", "1.0.0"],
    latestTag: "1.0.3",
    euRestricted: false,
  },
  {
    name: "parakeet-0-6b-ctc-en-us",
    displayName: "Parakeet 0.6b CTC en-US NIM",
    namespace: "nim/nvidia",
    tags: ["3.1.0", "3.1", "3", "3.0", "3.0.0"],
    latestTag: "3.1.0",
    euRestricted: false,
  },
  {
    name: "nvclip",
    displayName: "NV-CLIP",
    namespace: "nim/nvidia",
    tags: ["2.0.0", "latest", "1", "1.0.0", "1.0"],
    latestTag: "2.0.0",
    euRestricted: false,
  },
  {
    name: "nemotron-4-340b-reward",
    displayName: "Nemotron-4-340B-Reward",
    namespace: "nim/nvidia",
    tags: ["1.2.0", "1.2", "1", "latest"],
    latestTag: "1.2.0",
    euRestricted: false,
  },
  {
    name: "vista3d",
    displayName: "VISTA-3D NIM",
    namespace: "nim/nvidia",
    tags: ["latest", "1", "1.0.0", "1.0"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "codellama-13b-instruct",
    displayName: "CodeLlama-13B-Instruct",
    namespace: "nim/meta",
    tags: ["1.2.2", "1.2", "1", "latest"],
    latestTag: "1.2.2",
    euRestricted: false,
  },
  {
    name: "domino-automotive-aero",
    displayName: "DoMINO-Automotive-Aero NIM",
    namespace: "nim/nvidia",
    tags: ["2.1.0-41313772", "2.0.0", "1.0.0"],
    latestTag: "2.1.0-41313772",
    euRestricted: false,
  },
  {
    name: "nv-yolox-page-elements-v1",
    displayName: "NeMo Retriever YOLOX Structured Images v1",
    namespace: "nim/nvidia",
    tags: ["1.1.0-rtx"],
    latestTag: "1.1.0-rtx",
    euRestricted: false,
  },
  {
    name: "nemoretriever-graphic-elements-v1",
    displayName: "NeMo Retriever Graphic Elements v1",
    namespace: "nim/nvidia",
    tags: ["1.6", "1.6.0", "1.5", "1.5.0", "1.4.0"],
    latestTag: "1.6",
    euRestricted: false,
  },
  {
    name: "llama-3.2-1b-instruct",
    displayName: "Llama-3.2-1B-Instruct",
    namespace: "nim/meta",
    tags: ["1.12.0", "1.12", "1.10", "1.10.1", "1.8.6"],
    latestTag: "1.12.0",
    euRestricted: false,
  },
  {
    name: "qwen3-235b-a22b-fp8",
    displayName: "qwen3-235b-a22b-fp8",
    namespace: "nim/qwen",
    tags: ["1.0.0", "1.0", "latest"],
    latestTag: "1.0.0",
    euRestricted: false,
  },
  {
    name: "starcoderbase-15b",
    displayName: "StarCoderBase 15.5B",
    namespace: "nim/bigcode",
    tags: ["latest", "1", "1.5", "1.5.0"],
    latestTag: "1.5.0",
    euRestricted: false,
  },
  {
    name: "qwen3-next-80b-a3b-instruct",
    displayName: "qwen3-next-80b-a3b-instruct",
    namespace: "nim/qwen",
    tags: ["1.5.0-variant", "1.5", "1.0", "1", "1.0.0-variant"],
    latestTag: "1.5.0-variant",
    euRestricted: false,
  },
  {
    name: "mistral-nemo-minitron-8b-8k-instruct",
    displayName: "Mistral-NeMo-Minitron-8B-Instruct",
    namespace: "nim/nv-mistralai",
    tags: ["1.2.3", "1.2", "1", "latest"],
    latestTag: "1.2.3",
    euRestricted: false,
  },
  {
    name: "cosmos-reason2-8b",
    displayName: "Cosmos Reason-2-8B",
    namespace: "nim/nvidia",
    tags: ["1.6.0", "1", "latest", "1.6"],
    latestTag: "1.6.0",
    euRestricted: false,
  },
  {
    name: "llama-3-sqlcoder-8b",
    displayName: "Llama-3-SQLCoder-8B",
    namespace: "nim/defog",
    tags: ["1.2", "latest", "1", "1.2.3"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "corrdiff",
    displayName: "Earth-2 CorrDiff",
    namespace: "nim/nvidia",
    tags: ["latest", "1.0.0", "1", "1.0", "0.1.0"],
    latestTag: "1.0.0",
    euRestricted: false,
  },
  {
    name: "silma-9b-instruct-v1.0",
    displayName: "silma-9b-instruct-v1.0",
    namespace: "nim/silma-ai",
    tags: ["1.8", "latest", "1.8.4", "1"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "flux.1-schnell",
    displayName: "FLUX.1-schnell",
    namespace: "nim/black-forest-labs",
    tags: ["1.1.2", "1.1.1", "1.1.0", "1.1", "latest"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "stable-diffusion-3.5-large",
    displayName: "Stable Diffusion 3.5 Large",
    namespace: "nim/stabilityai",
    tags: ["1.0.2", "1.0.1", "1.0.0", "1.0", "latest"],
    latestTag: "1.0.2",
    euRestricted: false,
  },
  {
    name: "llama-3.2-nemoretriever-300m-embed-v2",
    displayName: "NVIDIA Retrieval QA Llama 3.2 300m Embedding v2",
    namespace: "nim/nvidia",
    tags: ["1.10.1", "1", "latest", "1.10.0", "1.10"],
    latestTag: "1.10.1",
    euRestricted: false,
  },
  {
    name: "llama-3-swallow-70b-instruct-v0.1",
    displayName: "Llama-3-Swallow-70B-Instruct-v0.1",
    namespace: "nim/tokyotech-llm",
    tags: ["latest", "1.1.2", "1.1", "1"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "parakeet-1-1b-ctc-en-us",
    displayName: "ASR Parakeet 1.1b CTC en-US",
    namespace: "nim/nvidia",
    tags: ["1.4", "1.4.0", "1.3.0", "1.2.0", "1.2"],
    latestTag: "1.4",
    euRestricted: false,
  },
  {
    name: "cosmos-predict1-7b-text2world",
    displayName: "Cosmos-Predict1-7B-Text2World",
    namespace: "nim/nvidia",
    tags: ["1.0.0", "1.0", "1", "latest"],
    latestTag: "1.0.0",
    euRestricted: false,
  },
  {
    name: "nv-embedqa-e5-v5-pb24h2",
    displayName: "NVIDIA Retrieval QA E5 Embedding v5 PB October 2024 (PB 24h2)",
    namespace: "nim/nvidia",
    tags: ["1.2.5", "1.2.4", "1.2.3", "1.2.2", "1.2.1"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "gemma-3-1b-it",
    displayName: "gemma-3-1b-it",
    namespace: "nim/google",
    tags: ["latest", "1.12", "1.12.0", "1"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "nemotron-parse",
    displayName: "Nemotron Parse",
    namespace: "nim/nvidia",
    tags: ["1.5.0", "1.5", "latest", "1"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "nemoretriever-ocr-v1",
    displayName: "NeMo Retriever OCR v1",
    namespace: "nim/nvidia",
    tags: ["1.2.1", "1.2", "latest", "1.2.0", "1"],
    latestTag: "1.2.1",
    euRestricted: false,
  },
  {
    name: "llama-3.2-nv-rerankqa-1b-v2-pb25h2",
    displayName: "NVIDIA Retrieval QA Llama 3.2 1B Reranking v2",
    namespace: "nim/nvidia",
    tags: ["1.9.2-stig-fips-x86", "1.9.1-stig-fips-x86", "1.9.0-stig-fips-x86"],
    latestTag: "1.9.2-stig-fips-x86",
    euRestricted: false,
  },
  {
    name: "deepseek-coder-v2-lite-instruct",
    displayName: "DeepSeek-Coder-V2-Lite-Instruct",
    namespace: "nim/deepseek-ai",
    tags: ["1.10.1", "1.10", "1", "latest"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "llama-3.2-nv-embedqa-1b-v2",
    displayName: "NVIDIA Retrieval QA Llama 3.2 1B Embedding v2",
    namespace: "nim/nvidia",
    tags: ["1.10.0", "1.10", "1.9.0", "1.9", "1.6"],
    latestTag: "1.10",
    euRestricted: false,
  },
  {
    name: "qwen3-next-80b-a3b-thinking",
    displayName: "Qwen3-Next-80B-A3B-Thinking",
    namespace: "nim/qwen",
    tags: ["1.0.0", "1", "1.0", "latest"],
    latestTag: "1.0.0",
    euRestricted: false,
  },
  {
    name: "llama-3.2-nv-rerankqa-1b-v2",
    displayName: "NVIDIA Retrieval QA Llama 3.2 1B Reranking v2",
    namespace: "nim/nvidia",
    tags: ["1.8.0", "1.8", "1.7.0", "1.7", "1.5.0"],
    latestTag: "1.8.0",
    euRestricted: false,
  },
  {
    name: "maxine-audio2face-2d",
    displayName: "Audio2Face-2D NIM",
    namespace: "nim/nvidia",
    tags: ["latest", "1.0.0", "1.0"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "gemma-2-9b-it",
    displayName: "Gemma-2-9B-IT",
    namespace: "nim/google",
    tags: ["1.4.0", "1.4", "1", "latest"],
    latestTag: "1.4.0",
    euRestricted: false,
  },
  {
    name: "llama-3.1-8b-instruct-pb25h2",
    displayName: "Llama-3.1-8B-Instruct (PB 25h2)",
    namespace: "nim/meta",
    tags: ["1.14.0-pb5.3", "1.14.0-pb5.3-stig-fips-x86-64", "1.14.0-pb5.2-stig-fips-x86-64", "1.14.0-pb5.2"],
    latestTag: "1.14.0-pb5.3",
    euRestricted: false,
  },
  {
    name: "nvidia-nemotron-nano-9b-v2",
    displayName: "NVIDIA-Nemotron-Nano-9B-v2",
    namespace: "nim/nvidia",
    tags: ["latest", "1", "1.12", "1.12.2"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "llama-3.1-nemotron-nano-8b-v1",
    displayName: "Llama-3.1-Nemotron-Nano-8B-v1",
    namespace: "nim/nvidia",
    tags: ["1.8.4", "1.8.3", "1.8", "latest", "1"],
    latestTag: "1.8.4",
    euRestricted: false,
  },
  {
    name: "deepseek-v31",
    displayName: "DeepSeek-V3.1",
    namespace: "nim/deepseek-ai",
    tags: ["latest", "1.0.0", "1.0"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "cosmos-predict1-7b-video2world",
    displayName: "Cosmos-Predict1-7B-Video2World",
    namespace: "nim/nvidia",
    tags: ["1.0.0", "latest", "1.0", "1"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "maxine-eye-contact",
    displayName: "Eye Contact",
    namespace: "nim/nvidia",
    tags: ["1.3", "1.3.0", "1.2.0", "1.2", "1.1.0"],
    latestTag: "1.3",
    euRestricted: false,
  },
  {
    name: "deepfake-image-detection",
    displayName: "deepfake-image-detection",
    namespace: "nim/hive",
    tags: ["latest", "1", "1.0.0", "1.0"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "parakeet-ctc-1.1b-asr",
    displayName: "ASR Parakeet CTC Riva 1.1b",
    namespace: "nim/nvidia",
    tags: ["1.0", "latest", "1.0.0"],
    latestTag: "1.0.0",
    euRestricted: false,
  },
  {
    name: "deepseek-r1",
    displayName: "DeepSeek-R1",
    namespace: "nim/deepseek-ai",
    tags: ["1.7.3", "1.7.2", "1.7.1", "1.7.0", "1.7"],
    latestTag: "1.7.3",
    euRestricted: false,
  },
  {
    name: "llama-3.1-405b-instruct",
    displayName: "Llama-3.1-405b-instruct",
    namespace: "nim/meta",
    tags: ["1.3.0", "1.3", "1.2.0", "1.2", "1.1.2"],
    latestTag: "1.3.0",
    euRestricted: false,
  },
  {
    name: "mixtral-8x7b-instruct-v0-1",
    displayName: "mixtral-8x7b-instruct-v0-1",
    namespace: "nim/mistralai",
    tags: ["1.12.0", "1.12", "1", "latest"],
    latestTag: "1.12.0",
    euRestricted: false,
  },
  {
    name: "llama-3-taiwan-70b-instruct",
    displayName: "Llama-3-Taiwan-70B-Instruct",
    namespace: "nim/yentinglin",
    tags: ["latest", "1.1.2", "1.1", "1"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "gpt-oss-20b",
    displayName: "GPT-OSS-20B",
    namespace: "nim/openai",
    tags: ["1.5.2-variant", "1.12.4", "1.12.3", "latest", "1.12.1"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "llama-3.1-8b-instruct-dgx-spark",
    displayName: "Llama-3.1-8b-Instruct-DGX-Spark",
    namespace: "nim/meta",
    tags: ["1.0", "1.0.0-variant", "1", "latest"],
    latestTag: "1.0.0-variant",
    euRestricted: false,
  },
  {
    name: "qwen3-235b-a22b-instruct-2507-fp8",
    displayName: "Qwen3-235B-A22B-Instruct-2507-FP8",
    namespace: "nim/qwen",
    tags: ["1.0", "latest", "1.0.0"],
    latestTag: "1.0",
    euRestricted: false,
  },
  {
    name: "openfold2",
    displayName: "OpenFold2",
    namespace: "nim/openfold",
    tags: ["2.3.0", "2.2", "2.2.0", "2.1", "2.1.0"],
    latestTag: "2",
    euRestricted: false,
  },
  {
    name: "llama-4-maverick-17b-128e-instruct",
    displayName: "Llama 4 Maverick 17B 128E Instruct",
    namespace: "nim/meta",
    tags: ["latest", "1.4", "1", "1.4.0"],
    latestTag: "1.4",
    euRestricted: true,
  },
  {
    name: "phi-4-mini-instruct",
    displayName: "phi-4-mini-instruct",
    namespace: "nim/microsoft",
    tags: ["1.12.0", "1.12", "latest", "1"],
    latestTag: "1.12",
    euRestricted: false,
  },
  {
    name: "llama-3.1-nemotron-nano-vl-8b-v1",
    displayName: "Llama 3.1 Nemotron Nano VL 8B v1",
    namespace: "nim/nvidia",
    tags: ["1.3.1", "1.3", "1.3.0", "1", "latest"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "phind-codellama-34b-v2-instruct",
    displayName: "Phind-CodeLlama-34B-v2-Instruct",
    namespace: "nim/phind",
    tags: ["1.2.3", "1.2", "1", "latest"],
    latestTag: "1.2.3",
    euRestricted: false,
  },
  {
    name: "llama-3.1-nemotron-ultra-253b-v1",
    displayName: "Llama-3.1-Nemotron-Ultra-253B-v1",
    namespace: "nim/nvidia",
    tags: ["1.12.0", "1.12", "1.8.4", "latest", "1"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "nv-embedqa-e5-v5-pb25h1",
    displayName: "NVIDIA Retrieval QA E5 Embedding v5 PB May 2025 (PB 25h1)",
    namespace: "nim/nvidia",
    tags: ["1.8.6", "1.8.5", "1.8.4", "1.8.3", "1.8.2"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "nemotron-3-nano",
    displayName: "Nemotron 3 Nano",
    namespace: "nim/nvidia",
    tags: ["1.7.0-variant", "1.7.0", "1", "1.5", "1.5.1-variant"],
    latestTag: "1.7.0-variant",
    euRestricted: false,
  },
  {
    name: "qwen3-32b",
    displayName: "Qwen3-32B",
    namespace: "nim/qwen",
    tags: ["1.0.0", "1.0", "latest"],
    latestTag: "1.0.0",
    euRestricted: false,
  },
  {
    name: "genmol",
    displayName: "NVIDIA NIM for GenMol",
    namespace: "nim/nvidia",
    tags: ["1.0.1", "1", "1.0", "latest", "1.0.0"],
    latestTag: "1.0",
    euRestricted: false,
  },
  {
    name: "proteinmpnn",
    displayName: "ProteinMPNN",
    namespace: "nim/ipd",
    tags: ["1.0.2", "latest", "1.0.1", "1", "1.0"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "qwen-2.5-72b-instruct",
    displayName: "qwen-2.5-72b-instruct",
    namespace: "nim/qwen",
    tags: ["latest", "1", "1.0", "1.0.0"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "mistral-small-3.2-24b-instruct-2506",
    displayName: "Mistral-Small-3.2-24B-Instruct-2506",
    namespace: "nim/mistralai",
    tags: ["1", "1.3", "1.3.1", "latest"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "gpt-oss-120b",
    displayName: "GPT-OSS-120B",
    namespace: "nim/openai",
    tags: ["1.5.2-variant", "1.12.4", "1.12.3", "1", "latest"],
    latestTag: "1.5.2-variant",
    euRestricted: false,
  },
  {
    name: "llama-3.1-8b-base",
    displayName: "Llama-3.1-8b-base",
    namespace: "nim/meta",
    tags: ["1.1.2", "1.1.1", "1.1", "1", "latest"],
    latestTag: "1.1.2",
    euRestricted: false,
  },
  {
    name: "nv-rerankqa-mistral-4b-v3",
    displayName: "NVIDIA Retrieval QA Mistral 4B Reranking v3",
    namespace: "nim/nvidia",
    tags: ["1.0.2", "1.0.1", "1.0.0"],
    latestTag: "1.0.2",
    euRestricted: false,
  },
  {
    name: "riva-nmt",
    displayName: "Riva NMT NIM",
    namespace: "nim/nvidia",
    tags: ["1.3", "1", "latest", "1.3.0"],
    latestTag: "1.3.0",
    euRestricted: false,
  },
  {
    name: "deepseek-r1-distill-qwen-7b",
    displayName: "Deepseek-R1-Distill-Qwen-7B",
    namespace: "nim/deepseek-ai",
    tags: ["1.1", "1.1.0", "1", "latest", "1.0"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "llama-3.2-nemoretriever-500m-rerank-v2",
    displayName: "Llama 3.2 NeMo Retriever 500M Rerank v2",
    namespace: "nim/nvidia",
    tags: ["1.8", "1.8.0", "1.7.0", "1.7", "latest"],
    latestTag: "1.8",
    euRestricted: false,
  },
  {
    name: "llama-3.1-nemotron-safety-guard-8b-v3",
    displayName: "Llama-3.1-Nemotron-Safety-Guard-8B-v3",
    namespace: "nim/nvidia",
    tags: ["latest", "1", "1.14", "1.14.0"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "fourcastnet",
    displayName: "Earth-2 FourCastNet",
    namespace: "nim/nvidia",
    tags: ["1.1", "1.1.0", "latest", "1.0.0", "1.0"],
    latestTag: "1.1",
    euRestricted: false,
  },
  {
    name: "nemoretriever-parse",
    displayName: "nemoretriever-parse",
    namespace: "nim/nvidia",
    tags: ["1.2.0", "latest", "1.2"],
    latestTag: "1.2",
    euRestricted: false,
  },
  {
    name: "llama-3.1-nemoguard-8b-content-safety",
    displayName: "Llama 3.1 NemoGuard 8B Content Safety",
    namespace: "nim/nvidia",
    tags: ["1.10.2", "1.10.1", "1.10", "1.0.0", "1.0"],
    latestTag: "1.10",
    euRestricted: false,
  },
  {
    name: "llama-4-scout-17b-16e-instruct",
    displayName: "Llama 4 Scout 17B 16E Instruct",
    namespace: "nim/meta",
    tags: ["1.3.2", "1.3.1", "1", "1.3.0", "1.3"],
    latestTag: "1",
    euRestricted: true,
  },
  {
    name: "llama-3.1-70b-instruct-pb25h1",
    displayName: "Llama-3.1-70B-Instruct October 2025 (PB 25h1)",
    namespace: "nim/meta",
    tags: ["1.10.0", "1", "1.10", "latest"],
    latestTag: "1.10",
    euRestricted: false,
  },
  {
    name: "llama-3.1-8b-instruct-pb25h1",
    displayName: "Llama-3.1-8B-Instruct PB 25h1 Overview",
    namespace: "nim/meta",
    tags: ["1.10", "latest", "1", "1.10.0"],
    latestTag: "1.10.0",
    euRestricted: false,
  },
  {
    name: "evo2",
    displayName: "Evo 2",
    namespace: "nim/arc",
    tags: ["2.1.0", "2.1", "latest", "2"],
    latestTag: "2.1.0",
    euRestricted: false,
  },
  {
    name: "llama-3.2-90b-vision-instruct",
    displayName: "Llama-3.2-90B-Vision-Instruct",
    namespace: "nim/meta",
    tags: ["1.1.1", "1.1.0", "1", "1.1", "latest"],
    latestTag: "1.1.1",
    euRestricted: true,
  },
  {
    name: "trellis",
    displayName: "TRELLIS",
    namespace: "nim/microsoft",
    tags: ["1.0.1", "1.0.0", "1.0", "1", "latest"],
    latestTag: "1.0.1",
    euRestricted: false,
  },
  {
    name: "riva-translate-4b-instruct-v1.1",
    displayName: "Riva-Translate-4b-Instruct",
    namespace: "nim/nvidia",
    tags: ["1.15", "latest", "1", "1.15.1"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "granite-3.3-8b-instruct",
    displayName: "Granite-3.3-8b-instruct",
    namespace: "nim/ibm-granite",
    tags: ["1.8.4", "1", "1.8", "latest"],
    latestTag: "1.8.4",
    euRestricted: false,
  },
  {
    name: "fastpitch-hifigan-tts",
    displayName: "TTS FastPitch HifiGAN Riva",
    namespace: "nim/nvidia",
    tags: ["1.0", "latest", "1.0.0"],
    latestTag: "1.0.0",
    euRestricted: false,
  },
  {
    name: "mistral-nemo-12b-instruct",
    displayName: "Mistral-Nemo-12B-Instruct",
    namespace: "nim/nv-mistralai",
    tags: ["1.8.0-rtx", "1.2", "1.2.2", "1", "latest"],
    latestTag: "1.8.0-rtx",
    euRestricted: false,
  },
  {
    name: "llama-nemotron-embed-vl-1b-v2",
    displayName: "Llama Nemotron VL Embed 1B",
    namespace: "nim/nvidia",
    tags: ["1.12.0"],
    latestTag: "1.12.0",
    euRestricted: false,
  },
  {
    name: "rfdiffusion",
    displayName: "RFdiffusion",
    namespace: "nim/ipd",
    tags: ["2.2", "2.2.0", "2.1", "2.1.0", "2.0"],
    latestTag: "2.2.0",
    euRestricted: false,
  },
  {
    name: "alphafold2-multimer",
    displayName: "AlphaFold2-Multimer",
    namespace: "nim/deepmind",
    tags: ["2", "latest", "2.1", "2.1.1", "1.0.0"],
    latestTag: "2",
    euRestricted: false,
  },
  {
    name: "glm-5",
    displayName: "GLM-5",
    namespace: "nim/zai-org",
    tags: ["1.7-variant", "1.7.0-variant", "latest"],
    latestTag: "1.7-variant",
    euRestricted: false,
  },
  {
    name: "maisi",
    displayName: "MAISI NIM",
    namespace: "nim/nvidia",
    tags: ["1.0.0", "1", "1.0", "latest"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "canary-1b",
    displayName: "Canary-1B ASR/AST Multilingual Offline Greedy",
    namespace: "nim/nvidia",
    tags: ["1.5.0", "1.5", "1.4.0", "latest", "1"],
    latestTag: "1.5.0",
    euRestricted: false,
  },
  {
    name: "parakeet-tdt-0.6b-v2",
    displayName: "Parakeet TDT 0.6B v2 Speech to Text",
    namespace: "nim/nvidia",
    tags: ["1.2.0", "1.2", "1.1", "1.1.0", "1.0.0"],
    latestTag: "1.2.0",
    euRestricted: false,
  },
  {
    name: "riva-tts",
    displayName: "Riva TTS NIM",
    namespace: "nim/nvidia",
    tags: ["1.3", "1", "latest", "1.3.0"],
    latestTag: "1.3.0",
    euRestricted: false,
  },
  {
    name: "deepseek-v3.1-terminus",
    displayName: "DeepSeek-V3.1-Terminus",
    namespace: "nim/deepseek-ai",
    tags: ["latest", "1.5.0-variant", "1.5-variant"],
    latestTag: "latest",
    euRestricted: false,
  },
  {
    name: "mixtral-8x7b-instruct-v01",
    displayName: "mixtral-8x7b-instruct-v0-1",
    namespace: "nim/mistralai",
    tags: ["1.8.4", "1.8", "1.3", "1.3.0", "1.2.1"],
    latestTag: "1.8.4",
    euRestricted: false,
  },
  {
    name: "eurollm-9b-instruct",
    displayName: "Eurollm-9b-instruct",
    namespace: "nim/utter-project",
    tags: ["1.8.5", "1.8", "latest", "1.8.4", "1"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "paddleocr",
    displayName: "NeMo Retriever PaddleOCR",
    namespace: "nim/baidu",
    tags: ["1.5", "1.4", "1.4.0", "1.3", "1.3.0"],
    latestTag: "1.5",
    euRestricted: false,
  },
  {
    name: "deepseek-v32-exp-nim",
    displayName: "DeepSeek-V3.2-Exp Container",
    namespace: "nim/deepseek-ai",
    tags: ["1.5.0-variant", "1", "latest", "1.5"],
    latestTag: "1.5.0-variant",
    euRestricted: false,
  },
  {
    name: "llama3.1-nemotron-nano-4b-v1.1",
    displayName: "Llama-3.1-Nemotron-Nano-4B-v1.1",
    namespace: "nim/nvidia",
    tags: ["1.8.5", "1.8.4", "latest", "1.8", "1"],
    latestTag: "1.8.5",
    euRestricted: false,
  },
  {
    name: "riva-asr",
    displayName: "Riva ASR NIM",
    namespace: "nim/nvidia",
    tags: ["1.3", "1", "latest", "1.3.0"],
    latestTag: "1.3.0",
    euRestricted: false,
  },
  {
    name: "magpie-tts-multilingual",
    displayName: "Magpie TTS Multilingual NIM",
    namespace: "nim/nvidia",
    tags: ["1.6", "1.6.0", "1.5.0", "1.5", "1.4.0"],
    latestTag: "1",
    euRestricted: false,
  },
  {
    name: "nv-embedqa-e5-v5-pb25h2",
    displayName: "NVIDIA Retrieval QA E5 Embedding v5",
    namespace: "nim/nvidia",
    tags: ["1.11.2-stig-fips-x86"],
    latestTag: "1.11.2-stig-fips-x86",
    euRestricted: false,
  },
  {
    name: "llama-3.1-swallow-8b-instruct-v0.1",
    displayName: "Llama-3.1-Swallow-8B-Instruct-v0.1",
    namespace: "nim/tokyotech-llm",
    tags: ["1", "latest", "1.3.2", "1.3"],
    latestTag: "1.3",
    euRestricted: false,
  },
  {
    name: "diffdock",
    displayName: "DiffDock",
    namespace: "nim/mit",
    tags: ["2.2", "2.2.0", "2.1", "2.1.0", "2.0.2"],
    latestTag: "2.2",
    euRestricted: false,
  },
];

